/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtmeFavoritesRouteImport } from './routes/@me/favorites'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as QueueChar123BracketChar125Char123RegionChar125RouteImport } from './routes/queue.{-$bracket}.{-$region}'
import { Route as RankingsClansChar123PageChar125RouteImport } from './routes/rankings/clans.{-$page}'
import { Route as RankingsGlobalChar123PageChar125RouteImport } from './routes/rankings/global.{-$page}'
import { Route as RankingsLegendsChar123PageChar125RouteImport } from './routes/rankings/legends.{-$page}'
import { Route as RankingsWeaponsChar123PageChar125RouteImport } from './routes/rankings/weapons.{-$page}'
import { Route as StatsClanClanIdRouteImport } from './routes/stats/clan/$clanId'
import { Route as StatsPlayerPlayerIdRouteImport } from './routes/stats/player/$playerId'
import { Route as Rankings1v1Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/1v1.{-$region}.{-$page}'
import { Route as Rankings2v2Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/2v2.{-$region}.{-$page}'
import { Route as Rankings3v3Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/3v3.{-$region}.{-$page}'
import { Route as StatsPlayerPlayerIdIndexRouteImport } from './routes/stats/player/$playerId.index'
import { Route as StatsPlayerPlayerId2v2RouteImport } from './routes/stats/player/$playerId.2v2'
import { Route as StatsPlayerPlayerIdLegendsRouteImport } from './routes/stats/player/$playerId.legends'
import { Route as StatsPlayerPlayerIdWeaponsRouteImport } from './routes/stats/player/$playerId.weapons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmeFavoritesRoute = AtmeFavoritesRouteImport.update({
  id: '/@me/favorites',
  path: '/@me/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueChar123BracketChar125Char123RegionChar125Route =
  QueueChar123BracketChar125Char123RegionChar125RouteImport.update({
    id: '/queue/{-$bracket}/{-$region}',
    path: '/queue/{-$bracket}/{-$region}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsClansChar123PageChar125Route =
  RankingsClansChar123PageChar125RouteImport.update({
    id: '/rankings/clans/{-$page}',
    path: '/rankings/clans/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsGlobalChar123PageChar125Route =
  RankingsGlobalChar123PageChar125RouteImport.update({
    id: '/rankings/global/{-$page}',
    path: '/rankings/global/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsLegendsChar123PageChar125Route =
  RankingsLegendsChar123PageChar125RouteImport.update({
    id: '/rankings/legends/{-$page}',
    path: '/rankings/legends/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsWeaponsChar123PageChar125Route =
  RankingsWeaponsChar123PageChar125RouteImport.update({
    id: '/rankings/weapons/{-$page}',
    path: '/rankings/weapons/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatsClanClanIdRoute = StatsClanClanIdRouteImport.update({
  id: '/stats/clan/$clanId',
  path: '/stats/clan/$clanId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPlayerPlayerIdRoute = StatsPlayerPlayerIdRouteImport.update({
  id: '/stats/player/$playerId',
  path: '/stats/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const Rankings1v1Char123RegionChar125Char123PageChar125Route =
  Rankings1v1Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/1v1/{-$region}/{-$page}',
    path: '/rankings/1v1/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Rankings2v2Char123RegionChar125Char123PageChar125Route =
  Rankings2v2Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/2v2/{-$region}/{-$page}',
    path: '/rankings/2v2/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Rankings3v3Char123RegionChar125Char123PageChar125Route =
  Rankings3v3Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/3v3/{-$region}/{-$page}',
    path: '/rankings/3v3/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatsPlayerPlayerIdIndexRoute =
  StatsPlayerPlayerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StatsPlayerPlayerIdRoute,
  } as any)
const StatsPlayerPlayerId2v2Route = StatsPlayerPlayerId2v2RouteImport.update({
  id: '/2v2',
  path: '/2v2',
  getParentRoute: () => StatsPlayerPlayerIdRoute,
} as any)
const StatsPlayerPlayerIdLegendsRoute =
  StatsPlayerPlayerIdLegendsRouteImport.update({
    id: '/legends',
    path: '/legends',
    getParentRoute: () => StatsPlayerPlayerIdRoute,
  } as any)
const StatsPlayerPlayerIdWeaponsRoute =
  StatsPlayerPlayerIdWeaponsRouteImport.update({
    id: '/weapons',
    path: '/weapons',
    getParentRoute: () => StatsPlayerPlayerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/rankings/': typeof RankingsIndexRoute
  '/queue/{-$bracket}/{-$region}': typeof QueueChar123BracketChar125Char123RegionChar125Route
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/rankings/legends/{-$page}': typeof RankingsLegendsChar123PageChar125Route
  '/rankings/weapons/{-$page}': typeof RankingsWeaponsChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRouteWithChildren
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/3v3/{-$region}/{-$page}': typeof Rankings3v3Char123RegionChar125Char123PageChar125Route
  '/stats/player/$playerId/2v2': typeof StatsPlayerPlayerId2v2Route
  '/stats/player/$playerId/legends': typeof StatsPlayerPlayerIdLegendsRoute
  '/stats/player/$playerId/weapons': typeof StatsPlayerPlayerIdWeaponsRoute
  '/stats/player/$playerId/': typeof StatsPlayerPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/rankings': typeof RankingsIndexRoute
  '/queue/{-$bracket}/{-$region}': typeof QueueChar123BracketChar125Char123RegionChar125Route
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/rankings/legends/{-$page}': typeof RankingsLegendsChar123PageChar125Route
  '/rankings/weapons/{-$page}': typeof RankingsWeaponsChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/3v3/{-$region}/{-$page}': typeof Rankings3v3Char123RegionChar125Char123PageChar125Route
  '/stats/player/$playerId/2v2': typeof StatsPlayerPlayerId2v2Route
  '/stats/player/$playerId/legends': typeof StatsPlayerPlayerIdLegendsRoute
  '/stats/player/$playerId/weapons': typeof StatsPlayerPlayerIdWeaponsRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/rankings/': typeof RankingsIndexRoute
  '/queue/{-$bracket}/{-$region}': typeof QueueChar123BracketChar125Char123RegionChar125Route
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/rankings/legends/{-$page}': typeof RankingsLegendsChar123PageChar125Route
  '/rankings/weapons/{-$page}': typeof RankingsWeaponsChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRouteWithChildren
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/3v3/{-$region}/{-$page}': typeof Rankings3v3Char123RegionChar125Char123PageChar125Route
  '/stats/player/$playerId/2v2': typeof StatsPlayerPlayerId2v2Route
  '/stats/player/$playerId/legends': typeof StatsPlayerPlayerIdLegendsRoute
  '/stats/player/$playerId/weapons': typeof StatsPlayerPlayerIdWeaponsRoute
  '/stats/player/$playerId/': typeof StatsPlayerPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@me/favorites'
    | '/rankings/'
    | '/queue/{-$bracket}/{-$region}'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/rankings/legends/{-$page}'
    | '/rankings/weapons/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/3v3/{-$region}/{-$page}'
    | '/stats/player/$playerId/2v2'
    | '/stats/player/$playerId/legends'
    | '/stats/player/$playerId/weapons'
    | '/stats/player/$playerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@me/favorites'
    | '/rankings'
    | '/queue/{-$bracket}/{-$region}'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/rankings/legends/{-$page}'
    | '/rankings/weapons/{-$page}'
    | '/stats/clan/$clanId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/3v3/{-$region}/{-$page}'
    | '/stats/player/$playerId/2v2'
    | '/stats/player/$playerId/legends'
    | '/stats/player/$playerId/weapons'
    | '/stats/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/@me/favorites'
    | '/rankings/'
    | '/queue/{-$bracket}/{-$region}'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/rankings/legends/{-$page}'
    | '/rankings/weapons/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/3v3/{-$region}/{-$page}'
    | '/stats/player/$playerId/2v2'
    | '/stats/player/$playerId/legends'
    | '/stats/player/$playerId/weapons'
    | '/stats/player/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmeFavoritesRoute: typeof AtmeFavoritesRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  QueueChar123BracketChar125Char123RegionChar125Route: typeof QueueChar123BracketChar125Char123RegionChar125Route
  RankingsClansChar123PageChar125Route: typeof RankingsClansChar123PageChar125Route
  RankingsGlobalChar123PageChar125Route: typeof RankingsGlobalChar123PageChar125Route
  RankingsLegendsChar123PageChar125Route: typeof RankingsLegendsChar123PageChar125Route
  RankingsWeaponsChar123PageChar125Route: typeof RankingsWeaponsChar123PageChar125Route
  StatsClanClanIdRoute: typeof StatsClanClanIdRoute
  StatsPlayerPlayerIdRoute: typeof StatsPlayerPlayerIdRouteWithChildren
  Rankings1v1Char123RegionChar125Char123PageChar125Route: typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  Rankings2v2Char123RegionChar125Char123PageChar125Route: typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  Rankings3v3Char123RegionChar125Char123PageChar125Route: typeof Rankings3v3Char123RegionChar125Char123PageChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@me/favorites': {
      id: '/@me/favorites'
      path: '/@me/favorites'
      fullPath: '/@me/favorites'
      preLoaderRoute: typeof AtmeFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/{-$bracket}/{-$region}': {
      id: '/queue/{-$bracket}/{-$region}'
      path: '/queue/{-$bracket}/{-$region}'
      fullPath: '/queue/{-$bracket}/{-$region}'
      preLoaderRoute: typeof QueueChar123BracketChar125Char123RegionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/clans/{-$page}': {
      id: '/rankings/clans/{-$page}'
      path: '/rankings/clans/{-$page}'
      fullPath: '/rankings/clans/{-$page}'
      preLoaderRoute: typeof RankingsClansChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/global/{-$page}': {
      id: '/rankings/global/{-$page}'
      path: '/rankings/global/{-$page}'
      fullPath: '/rankings/global/{-$page}'
      preLoaderRoute: typeof RankingsGlobalChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/legends/{-$page}': {
      id: '/rankings/legends/{-$page}'
      path: '/rankings/legends/{-$page}'
      fullPath: '/rankings/legends/{-$page}'
      preLoaderRoute: typeof RankingsLegendsChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/weapons/{-$page}': {
      id: '/rankings/weapons/{-$page}'
      path: '/rankings/weapons/{-$page}'
      fullPath: '/rankings/weapons/{-$page}'
      preLoaderRoute: typeof RankingsWeaponsChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/clan/$clanId': {
      id: '/stats/clan/$clanId'
      path: '/stats/clan/$clanId'
      fullPath: '/stats/clan/$clanId'
      preLoaderRoute: typeof StatsClanClanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/player/$playerId': {
      id: '/stats/player/$playerId'
      path: '/stats/player/$playerId'
      fullPath: '/stats/player/$playerId'
      preLoaderRoute: typeof StatsPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/1v1/{-$region}/{-$page}': {
      id: '/rankings/1v1/{-$region}/{-$page}'
      path: '/rankings/1v1/{-$region}/{-$page}'
      fullPath: '/rankings/1v1/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings1v1Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/2v2/{-$region}/{-$page}': {
      id: '/rankings/2v2/{-$region}/{-$page}'
      path: '/rankings/2v2/{-$region}/{-$page}'
      fullPath: '/rankings/2v2/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings2v2Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/3v3/{-$region}/{-$page}': {
      id: '/rankings/3v3/{-$region}/{-$page}'
      path: '/rankings/3v3/{-$region}/{-$page}'
      fullPath: '/rankings/3v3/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings3v3Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/player/$playerId/': {
      id: '/stats/player/$playerId/'
      path: '/'
      fullPath: '/stats/player/$playerId/'
      preLoaderRoute: typeof StatsPlayerPlayerIdIndexRouteImport
      parentRoute: typeof StatsPlayerPlayerIdRoute
    }
    '/stats/player/$playerId/2v2': {
      id: '/stats/player/$playerId/2v2'
      path: '/2v2'
      fullPath: '/stats/player/$playerId/2v2'
      preLoaderRoute: typeof StatsPlayerPlayerId2v2RouteImport
      parentRoute: typeof StatsPlayerPlayerIdRoute
    }
    '/stats/player/$playerId/legends': {
      id: '/stats/player/$playerId/legends'
      path: '/legends'
      fullPath: '/stats/player/$playerId/legends'
      preLoaderRoute: typeof StatsPlayerPlayerIdLegendsRouteImport
      parentRoute: typeof StatsPlayerPlayerIdRoute
    }
    '/stats/player/$playerId/weapons': {
      id: '/stats/player/$playerId/weapons'
      path: '/weapons'
      fullPath: '/stats/player/$playerId/weapons'
      preLoaderRoute: typeof StatsPlayerPlayerIdWeaponsRouteImport
      parentRoute: typeof StatsPlayerPlayerIdRoute
    }
  }
}

interface StatsPlayerPlayerIdRouteChildren {
  StatsPlayerPlayerId2v2Route: typeof StatsPlayerPlayerId2v2Route
  StatsPlayerPlayerIdLegendsRoute: typeof StatsPlayerPlayerIdLegendsRoute
  StatsPlayerPlayerIdWeaponsRoute: typeof StatsPlayerPlayerIdWeaponsRoute
  StatsPlayerPlayerIdIndexRoute: typeof StatsPlayerPlayerIdIndexRoute
}

const StatsPlayerPlayerIdRouteChildren: StatsPlayerPlayerIdRouteChildren = {
  StatsPlayerPlayerId2v2Route: StatsPlayerPlayerId2v2Route,
  StatsPlayerPlayerIdLegendsRoute: StatsPlayerPlayerIdLegendsRoute,
  StatsPlayerPlayerIdWeaponsRoute: StatsPlayerPlayerIdWeaponsRoute,
  StatsPlayerPlayerIdIndexRoute: StatsPlayerPlayerIdIndexRoute,
}

const StatsPlayerPlayerIdRouteWithChildren =
  StatsPlayerPlayerIdRoute._addFileChildren(StatsPlayerPlayerIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmeFavoritesRoute: AtmeFavoritesRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  QueueChar123BracketChar125Char123RegionChar125Route:
    QueueChar123BracketChar125Char123RegionChar125Route,
  RankingsClansChar123PageChar125Route: RankingsClansChar123PageChar125Route,
  RankingsGlobalChar123PageChar125Route: RankingsGlobalChar123PageChar125Route,
  RankingsLegendsChar123PageChar125Route:
    RankingsLegendsChar123PageChar125Route,
  RankingsWeaponsChar123PageChar125Route:
    RankingsWeaponsChar123PageChar125Route,
  StatsClanClanIdRoute: StatsClanClanIdRoute,
  StatsPlayerPlayerIdRoute: StatsPlayerPlayerIdRouteWithChildren,
  Rankings1v1Char123RegionChar125Char123PageChar125Route:
    Rankings1v1Char123RegionChar125Char123PageChar125Route,
  Rankings2v2Char123RegionChar125Char123PageChar125Route:
    Rankings2v2Char123RegionChar125Char123PageChar125Route,
  Rankings3v3Char123RegionChar125Char123PageChar125Route:
    Rankings3v3Char123RegionChar125Char123PageChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
