import type { PR } from "./parsePowerRankingsPage"

export const powerRankingsMock: PR[] = [
    {
        rank: 1,
        name: "acno?",
        earnings: "$95,614.00",
        t1: 17,
        t2: 3,
        t3: 1,
        t8: 23,
        t32: 24,
        socials: { twitter: "AcnoBH", twitch: "TPAcno" },
    },
    {
        rank: 1,
        name: "Blaze",
        earnings: "$50,209.50",
        t1: 17,
        t2: 4,
        t3: 0,
        t8: 26,
        t32: 31,
        socials: { twitter: "BlazeBH_", twitch: "BlazeBH_" },
    },
    {
        rank: 3,
        name: "simpLe",
        earnings: "$66,680.00",
        t1: 8,
        t2: 12,
        t3: 3,
        t8: 28,
        t32: 30,
        socials: { twitter: "simpLetastico", twitch: "simpletastico" },
    },
    {
        rank: 4,
        name: "hysen",
        earnings: "$30,664.17",
        t1: 0,
        t2: 7,
        t3: 5,
        t8: 19,
        t32: 27,
        socials: { twitter: "Hysennnn", twitch: "Hysennnn" },
    },
    {
        rank: 5,
        name: "TM.",
        earnings: "$6,105.00",
        t1: 0,
        t2: 2,
        t3: 0,
        t8: 8,
        t32: 20,
        socials: { twitch: "TM_bh" },
    },
    {
        rank: 6,
        name: "Fozey",
        earnings: "$12,518.40",
        t1: 0,
        t2: 2,
        t3: 7,
        t8: 19,
        t32: 31,
        socials: { twitter: "Fozeyxd", twitch: "fozeyxd" },
    },
    {
        rank: 7,
        name: "Swata",
        earnings: "$26,180.00",
        t1: 0,
        t2: 1,
        t3: 1,
        t8: 7,
        t32: 22,
        socials: { twitter: "Swaata" },
    },
    {
        rank: 8,
        name: "Macheeeete",
        earnings: "$25,220.00",
        t1: 0,
        t2: 2,
        t3: 8,
        t8: 21,
        t32: 31,
        socials: { twitter: "macheeeete", twitch: "Macheeeete" },
    },
    {
        rank: 9,
        name: "VipR3",
        earnings: "$32,847.50",
        t1: 2,
        t2: 6,
        t3: 5,
        t8: 33,
        t32: 45,
        socials: { twitter: "The_VipR3", twitch: "VipR3" },
    },
    {
        rank: 10,
        name: "Delta",
        earnings: "$4,150.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 3,
        t32: 8,
        socials: { twitter: "HazerDelta", twitch: "hazer_deltabh" },
    },
    {
        rank: 11,
        name: "Spyrox",
        earnings: "$1,720.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 3,
        t32: 12,
        socials: {},
    },
    {
        rank: 12,
        name: "Koko",
        earnings: "$3,000.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 2,
        t32: 5,
        socials: { twitter: "KebabKoko", twitch: "KokoN4" },
    },
    {
        rank: 13,
        name: "Sarme",
        earnings: "$5,000.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 2,
        t32: 11,
        socials: { twitter: "SarmeBH", twitch: "sarme_bh" },
    },
    {
        rank: 14,
        name: "TheNinja729",
        earnings: "$20,754.50",
        t1: 1,
        t2: 2,
        t3: 4,
        t8: 18,
        t32: 32,
        socials: { twitter: "TheNinja729" },
    },
    {
        rank: 14,
        name: "Pavelski",
        earnings: "$46,994.00",
        t1: 0,
        t2: 2,
        t3: 4,
        t8: 18,
        t32: 30,
        socials: { twitter: "PavelskiBH", twitch: "PavelskiBH" },
    },
    {
        rank: 16,
        name: "Blew",
        earnings: "$40,040.00",
        t1: 8,
        t2: 3,
        t3: 2,
        t8: 27,
        t32: 36,
        socials: { twitter: "RealBlew", twitch: "Blews" },
    },
    {
        rank: 17,
        name: "Solarson",
        earnings: "$3,000.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 3,
        t32: 21,
        socials: { twitter: "SolarsonTK", twitch: "SolarsonTK" },
    },
    {
        rank: 18,
        name: "Spectre.",
        earnings: "$3,825.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 3,
        t32: 7,
        socials: { twitter: "SpectreBH", twitch: "spectrebh" },
    },
    {
        rank: 19,
        name: "zyder",
        earnings: "$7,745.00",
        t1: 0,
        t2: 0,
        t3: 1,
        t8: 10,
        t32: 25,
        socials: { twitter: "itsreallyzyder", twitch: "jkzyder100" },
    },
    {
        rank: 20,
        name: "Cedero",
        earnings: "$5,785.00",
        t1: 0,
        t2: 0,
        t3: 2,
        t8: 12,
        t32: 33,
        socials: { twitter: "CederoBH", twitch: "CederoBH" },
    },
    {
        rank: 21,
        name: "720polyshot",
        earnings: "$7,884.00",
        t1: 0,
        t2: 0,
        t3: 1,
        t8: 5,
        t32: 19,
        socials: { twitch: "720polyskishot" },
    },
    {
        rank: 22,
        name: "KiXe",
        earnings: "$3,500.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 2,
        t32: 19,
        socials: { twitter: "KiXeOfficial", twitch: "KiXe" },
    },
    {
        rank: 23,
        name: "Snowb4ll",
        earnings: "$870.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 1,
        t32: 28,
        socials: { twitter: "The_Snowb4ll", twitch: "Snowb4ll" },
    },
    {
        rank: 24,
        name: "Seijaru",
        earnings: "$1,575.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 1,
        t32: 5,
        socials: { twitter: "Seijaru", twitch: "Seijaru" },
    },
    {
        rank: 25,
        name: "Zapapy",
        earnings: "$4,550.00",
        t1: 0,
        t2: 2,
        t3: 0,
        t8: 10,
        t32: 26,
        socials: {},
    },
    {
        rank: 25,
        name: "Stikieuh",
        earnings: "$3,672.50",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 14,
        t32: 32,
        socials: {},
    },
    {
        rank: 27,
        name: "Kresuu",
        earnings: "$1,280.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 1,
        t32: 12,
        socials: { twitter: "Kresuuu", twitch: "Kresuuu" },
    },
    {
        rank: 28,
        name: "M for Mini",
        earnings: "$12,568.17",
        t1: 0,
        t2: 2,
        t3: 3,
        t8: 17,
        t32: 33,
        socials: { twitter: "M_for_Mini" },
    },
    {
        rank: 29,
        name: "Scyotic",
        earnings: "$875.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 1,
        t32: 10,
        socials: { twitter: "Scyotic", twitch: "Scyotic" },
    },
    {
        rank: 30,
        name: "Neeze",
        earnings: "$10,983.67",
        t1: 0,
        t2: 1,
        t3: 1,
        t8: 10,
        t32: 28,
        socials: { twitter: "Neeze3xi", twitch: "neeze3xi" },
    },
    {
        rank: 31,
        name: "FryDasOle",
        earnings: "$2,150.00",
        t1: 0,
        t2: 1,
        t3: 0,
        t8: 1,
        t32: 17,
        socials: { twitter: "FryDasOle", twitch: "FryDasOleBH" },
    },
    {
        rank: 32,
        name: "Urbador",
        earnings: "$500.00",
        t1: 0,
        t2: 0,
        t3: 0,
        t8: 0,
        t32: 8,
        socials: { twitter: "UrbadorBH_", twitch: "UrbadorBH" },
    },
]
