/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as TwitterRouteImport } from './routes/twitter'
import { Route as KofiRouteImport } from './routes/kofi'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as StatsMeRouteImport } from './routes/stats/me'
import { Route as RankingsGlobalRouteImport } from './routes/rankings/global'
import { Route as PPlayerIdRouteImport } from './routes/p/$playerId'
import { Route as LeaderboardSplatRouteImport } from './routes/leaderboard/$'
import { Route as CClanIdRouteImport } from './routes/c/$clanId'
import { Route as AtmeFavoritesRouteImport } from './routes/@me/favorites'
import { Route as StatsPlayerPlayerIdRouteImport } from './routes/stats/player/$playerId'
import { Route as StatsClanClanIdRouteImport } from './routes/stats/clan/$clanId'
import { Route as RankingsClansChar123PageChar125RouteImport } from './routes/rankings/clans.{-$page}'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as RankingsPowerBracketRegionRouteImport } from './routes/rankings/power.$bracket.$region'
import { Route as Rankings2v2Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/2v2.{-$region}.{-$page}'
import { Route as Rankings1v1Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/1v1.{-$region}.{-$page}'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterRoute = TwitterRouteImport.update({
  id: '/twitter',
  path: '/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const KofiRoute = KofiRouteImport.update({
  id: '/kofi',
  path: '/kofi',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsMeRoute = StatsMeRouteImport.update({
  id: '/stats/me',
  path: '/stats/me',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsGlobalRoute = RankingsGlobalRouteImport.update({
  id: '/rankings/global',
  path: '/rankings/global',
  getParentRoute: () => rootRouteImport,
} as any)
const PPlayerIdRoute = PPlayerIdRouteImport.update({
  id: '/p/$playerId',
  path: '/p/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardSplatRoute = LeaderboardSplatRouteImport.update({
  id: '/leaderboard/$',
  path: '/leaderboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CClanIdRoute = CClanIdRouteImport.update({
  id: '/c/$clanId',
  path: '/c/$clanId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmeFavoritesRoute = AtmeFavoritesRouteImport.update({
  id: '/@me/favorites',
  path: '/@me/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPlayerPlayerIdRoute = StatsPlayerPlayerIdRouteImport.update({
  id: '/stats/player/$playerId',
  path: '/stats/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsClanClanIdRoute = StatsClanClanIdRouteImport.update({
  id: '/stats/clan/$clanId',
  path: '/stats/clan/$clanId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsClansChar123PageChar125Route =
  RankingsClansChar123PageChar125RouteImport.update({
    id: '/rankings/clans/{-$page}',
    path: '/rankings/clans/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPowerBracketRegionRoute =
  RankingsPowerBracketRegionRouteImport.update({
    id: '/rankings/power/$bracket/$region',
    path: '/rankings/power/$bracket/$region',
    getParentRoute: () => rootRouteImport,
  } as any)
const Rankings2v2Char123RegionChar125Char123PageChar125Route =
  Rankings2v2Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/2v2/{-$region}/{-$page}',
    path: '/rankings/2v2/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Rankings1v1Char123RegionChar125Char123PageChar125Route =
  Rankings1v1Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/1v1/{-$region}/{-$page}',
    path: '/rankings/1v1/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/c/$clanId': typeof CClanIdRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$playerId': typeof PPlayerIdRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/$bracket/$region': typeof RankingsPowerBracketRegionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/c/$clanId': typeof CClanIdRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$playerId': typeof PPlayerIdRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings': typeof RankingsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/$bracket/$region': typeof RankingsPowerBracketRegionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/c/$clanId': typeof CClanIdRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$playerId': typeof PPlayerIdRoute
  '/rankings/global': typeof RankingsGlobalRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/$bracket/$region': typeof RankingsPowerBracketRegionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/c/$clanId'
    | '/leaderboard/$'
    | '/p/$playerId'
    | '/rankings/global'
    | '/stats/me'
    | '/rankings/'
    | '/api/trpc/$'
    | '/rankings/clans/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/$bracket/$region'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/c/$clanId'
    | '/leaderboard/$'
    | '/p/$playerId'
    | '/rankings/global'
    | '/stats/me'
    | '/rankings'
    | '/api/trpc/$'
    | '/rankings/clans/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/$bracket/$region'
  id:
    | '__root__'
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/c/$clanId'
    | '/leaderboard/$'
    | '/p/$playerId'
    | '/rankings/global'
    | '/stats/me'
    | '/rankings/'
    | '/api/trpc/$'
    | '/rankings/clans/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/$bracket/$region'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcRoute: typeof CalcRoute
  DiscordRoute: typeof DiscordRoute
  DonateRoute: typeof DonateRoute
  GithubRoute: typeof GithubRoute
  KofiRoute: typeof KofiRoute
  TwitterRoute: typeof TwitterRoute
  WikiRoute: typeof WikiRoute
  AtmeFavoritesRoute: typeof AtmeFavoritesRoute
  CClanIdRoute: typeof CClanIdRoute
  LeaderboardSplatRoute: typeof LeaderboardSplatRoute
  PPlayerIdRoute: typeof PPlayerIdRoute
  RankingsGlobalRoute: typeof RankingsGlobalRoute
  StatsMeRoute: typeof StatsMeRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  RankingsClansChar123PageChar125Route: typeof RankingsClansChar123PageChar125Route
  StatsClanClanIdRoute: typeof StatsClanClanIdRoute
  StatsPlayerPlayerIdRoute: typeof StatsPlayerPlayerIdRoute
  Rankings1v1Char123RegionChar125Char123PageChar125Route: typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  Rankings2v2Char123RegionChar125Char123PageChar125Route: typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  RankingsPowerBracketRegionRoute: typeof RankingsPowerBracketRegionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter': {
      id: '/twitter'
      path: '/twitter'
      fullPath: '/twitter'
      preLoaderRoute: typeof TwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kofi': {
      id: '/kofi'
      path: '/kofi'
      fullPath: '/kofi'
      preLoaderRoute: typeof KofiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/me': {
      id: '/stats/me'
      path: '/stats/me'
      fullPath: '/stats/me'
      preLoaderRoute: typeof StatsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/global': {
      id: '/rankings/global'
      path: '/rankings/global'
      fullPath: '/rankings/global'
      preLoaderRoute: typeof RankingsGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$playerId': {
      id: '/p/$playerId'
      path: '/p/$playerId'
      fullPath: '/p/$playerId'
      preLoaderRoute: typeof PPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$': {
      id: '/leaderboard/$'
      path: '/leaderboard/$'
      fullPath: '/leaderboard/$'
      preLoaderRoute: typeof LeaderboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$clanId': {
      id: '/c/$clanId'
      path: '/c/$clanId'
      fullPath: '/c/$clanId'
      preLoaderRoute: typeof CClanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@me/favorites': {
      id: '/@me/favorites'
      path: '/@me/favorites'
      fullPath: '/@me/favorites'
      preLoaderRoute: typeof AtmeFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/player/$playerId': {
      id: '/stats/player/$playerId'
      path: '/stats/player/$playerId'
      fullPath: '/stats/player/$playerId'
      preLoaderRoute: typeof StatsPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/clan/$clanId': {
      id: '/stats/clan/$clanId'
      path: '/stats/clan/$clanId'
      fullPath: '/stats/clan/$clanId'
      preLoaderRoute: typeof StatsClanClanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/clans/{-$page}': {
      id: '/rankings/clans/{-$page}'
      path: '/rankings/clans/{-$page}'
      fullPath: '/rankings/clans/{-$page}'
      preLoaderRoute: typeof RankingsClansChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/power/$bracket/$region': {
      id: '/rankings/power/$bracket/$region'
      path: '/rankings/power/$bracket/$region'
      fullPath: '/rankings/power/$bracket/$region'
      preLoaderRoute: typeof RankingsPowerBracketRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/2v2/{-$region}/{-$page}': {
      id: '/rankings/2v2/{-$region}/{-$page}'
      path: '/rankings/2v2/{-$region}/{-$page}'
      fullPath: '/rankings/2v2/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings2v2Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/1v1/{-$region}/{-$page}': {
      id: '/rankings/1v1/{-$region}/{-$page}'
      path: '/rankings/1v1/{-$region}/{-$page}'
      fullPath: '/rankings/1v1/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings1v1Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcRoute: CalcRoute,
  DiscordRoute: DiscordRoute,
  DonateRoute: DonateRoute,
  GithubRoute: GithubRoute,
  KofiRoute: KofiRoute,
  TwitterRoute: TwitterRoute,
  WikiRoute: WikiRoute,
  AtmeFavoritesRoute: AtmeFavoritesRoute,
  CClanIdRoute: CClanIdRoute,
  LeaderboardSplatRoute: LeaderboardSplatRoute,
  PPlayerIdRoute: PPlayerIdRoute,
  RankingsGlobalRoute: RankingsGlobalRoute,
  StatsMeRoute: StatsMeRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  RankingsClansChar123PageChar125Route: RankingsClansChar123PageChar125Route,
  StatsClanClanIdRoute: StatsClanClanIdRoute,
  StatsPlayerPlayerIdRoute: StatsPlayerPlayerIdRoute,
  Rankings1v1Char123RegionChar125Char123PageChar125Route:
    Rankings1v1Char123RegionChar125Char123PageChar125Route,
  Rankings2v2Char123RegionChar125Char123PageChar125Route:
    Rankings2v2Char123RegionChar125Char123PageChar125Route,
  RankingsPowerBracketRegionRoute: RankingsPowerBracketRegionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
