#!/usr/bin/env node
/**
 * Deterministic seed-SQL generator for the D1 database.
 *
 * Writes chunked, FK-ordered `INSERT` statements that stay well under D1's
 * 100 KB per-statement limit. It is checked in and reproducible: the same
 * `--seed` always produces the same data, so a seeded database can be recreated
 * exactly.
 *
 * Nothing here touches a database. Seeding is a one-off, manual operation:
 *
 *   pnpm db:seed -- --rows=1000000
 *   pnpm db:seed:verify                      # apply + check in local SQLite
 *   pnpm dlx wrangler d1 execute corehalla --remote \
 *       --file=packages/db/seed/generated/seed.sql --yes
 *
 * (wrangler is not a repo dependency; `pnpm dlx` fetches it. For the old
 * Supabase data use `scripts/import-postgres.mts` instead — see the README.)
 *
 * Flags: --rows=N (default 1_000_000), --chunk=N (default 150), --seed=N
 * (default 1), --timestamp=MS (default now), --out=PATH.
 *
 * `lastUpdated`/`createdAt` default to the current time so the crawler's
 * "delete rows older than two days" pass does not immediately drop the seed.
 */
import { createWriteStream } from "node:fs"
import { mkdir } from "node:fs/promises"
import { once } from "node:events"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { insertStatements, quoteSql, type Sql } from "./sql.mts"

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..")

export type SeedOptions = {
    readonly rows: number
    readonly chunk: number
    readonly seed: number
    readonly timestamp: number
}

const BH_PLAYER_DATA_COLUMNS = [
    "id",
    "name",
    "lastUpdated",
    "xp",
    "level",
    "tier",
    "games",
    "wins",
    "rating",
    "peakRating",
    "rankedGames",
    "rankedWins",
    "region",
    "damageDealt",
    "damageTaken",
    "kos",
    "falls",
    "suicides",
    "teamKos",
    "matchTime",
    "damageUnarmed",
    "koUnarmed",
    "matchTimeUnarmed",
    "koThrownItem",
    "damageThrownItem",
    "koGadgets",
    "damageGadgets",
] as const

const BH_PLAYER_LEGEND_COLUMNS = [
    "player_id",
    "lastUpdated",
    "legend_id",
    "damageDealt",
    "damageTaken",
    "kos",
    "falls",
    "suicides",
    "teamKos",
    "matchTime",
    "games",
    "wins",
    "damageUnarmed",
    "damageThrownItem",
    "damageWeaponOne",
    "damageWeaponTwo",
    "damageGadgets",
    "koUnarmed",
    "koThrownItem",
    "koWeaponOne",
    "koWeaponTwo",
    "koGadgets",
    "timeHeldWeaponOne",
    "timeHeldWeaponTwo",
    "xp",
    "level",
] as const

const BH_PLAYER_WEAPON_COLUMNS = [
    "player_id",
    "lastUpdated",
    "weapon_name",
    "kos",
    "matchTime",
    "games",
    "wins",
    "damageDealt",
    "xp",
    "level",
] as const

const WEAPONS = [
    "Sword",
    "Axe",
    "Spear",
    "Bow",
    "Blasters",
    "Katar",
    "Rocket Lance",
    "Hammer",
    "Scythe",
    "Cannon",
    "Gauntlets",
    "Orb",
    "Greatsword",
    "Chakram",
    "Battle Boots",
] as const

const TIERS = [
    "Tin",
    "Bronze",
    "Silver",
    "Gold",
    "Platinum",
    "Diamond",
    "Valhallan",
] as const

const REGIONS = [
    "us-e",
    "eu",
    "sea",
    "brz",
    "aus",
    "us-w",
    "jpn",
    "sa",
    "me",
] as const

/** mulberry32 — small, fast, deterministic. */
const makeRandom = (seed: number) => {
    let state = seed >>> 0

    return () => {
        state = (state + 0x6d2b79f5) >>> 0
        let t = state
        t = Math.imul(t ^ (t >>> 15), t | 1)
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296
    }
}

/** The seed's `chunk` flag is a row count; the writer also enforces D1's byte budget. */
const insert = (
    table: string,
    columns: readonly string[],
    rows: readonly (readonly Sql[])[],
    chunk: number,
) => insertStatements(table, columns, rows, { rows: chunk })

/**
 * Yields the seed file one statement at a time, so callers can stream it to a
 * file (the CLI) or straight into a local SQLite database (the verifier)
 * without holding millions of rows in memory.
 */
export function* generateSeedSql(options: SeedOptions): Generator<string> {
    const { rows, chunk, seed, timestamp } = options
    const random = makeRandom(seed)
    const stat = () => Math.floor(random() * 100_000)
    const playerId = (index: number) => `seed-${index}`
    const playerName = (index: number) => `Player ${index}`
    const legendId = (index: number) => 1 + (index % 4)

    yield "-- Generated by packages/db/scripts/seed.mts — do not edit."
    yield `-- rows=${rows} chunk=${chunk} seed=${seed} timestamp=${timestamp}`

    // Clans first (independent, but keeps the file readable).
    const clanCount = Math.max(1, Math.floor(rows / 50))
    const clans: Sql[][] = Array.from({ length: clanCount }, (_, i) => [
        `clan-${i}`,
        `Clan ${i}`,
        1_500_000_000 + i,
        (clanCount - i) * 1000,
    ])

    for (const statement of insert(
        "BHClan",
        ["id", "name", "created", "xp"],
        clans,
        chunk,
    )) {
        yield statement
    }

    // Players, then their legends/weapons/aliases so foreign keys hold.
    for (let start = 0; start < rows; start += chunk) {
        const end = Math.min(start + chunk, rows)
        const players: Sql[][] = []
        const legends: Sql[][] = []
        const weapons: Sql[][] = []
        const aliases: Sql[][] = []

        for (let i = start; i < end; i++) {
            const id = playerId(i)

            players.push([
                id,
                playerName(i),
                timestamp,
                (rows - i) * 10,
                1 + (i % 100),
                TIERS[i % TIERS.length] ?? "Gold",
                1000 + stat(),
                100 + stat(),
                800 + (i % 1500),
                900 + (i % 1600),
                100 + stat(),
                10 + stat(),
                REGIONS[i % REGIONS.length] ?? "us-e",
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
                stat(),
            ])

            for (let slot = 0; slot < 3; slot++) {
                const legend = legendId(i + slot)

                legends.push([
                    id,
                    timestamp,
                    legend,
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    (rows - i) * 5,
                    1 + (i % 50),
                ])

                weapons.push([
                    id,
                    timestamp,
                    WEAPONS[(i + slot) % WEAPONS.length] ?? "Sword",
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    stat(),
                    (rows - i) * 3,
                    1 + (i % 40),
                ])
            }

            aliases.push([id, playerName(i), timestamp, true])
            aliases.push([id, `Alias ${i}`, timestamp, i % 5 !== 0])
        }

        for (const statement of insert(
            "BHPlayerData",
            BH_PLAYER_DATA_COLUMNS,
            players,
            chunk,
        )) {
            yield statement
        }

        for (const statement of insert(
            "BHPlayerLegend",
            BH_PLAYER_LEGEND_COLUMNS,
            legends,
            chunk,
        )) {
            yield statement
        }

        for (const statement of insert(
            "BHPlayerWeapon",
            BH_PLAYER_WEAPON_COLUMNS,
            weapons,
            chunk,
        )) {
            yield statement
        }

        for (const statement of insert(
            "BHPlayerAlias",
            ["playerId", "alias", "createdAt", "public"],
            aliases,
            chunk,
        )) {
            yield statement
        }
    }

    yield `INSERT OR IGNORE INTO "CrawlProgress" ("id", "name", "lastUpdated", "progress") VALUES ('Crawler', 'Crawler', ${quoteSql(timestamp)}, 1);`
}

type CliOptions = SeedOptions & { readonly out: string }

const parseArgs = (argv: readonly string[]): CliOptions => {
    const flag = (name: string) =>
        argv.find((arg) => arg.startsWith(`--${name}=`))?.slice(name.length + 3)

    const number = (name: string, fallback: number) => {
        const value = Number(flag(name) ?? fallback)

        return Number.isFinite(value) && value > 0
            ? Math.floor(value)
            : fallback
    }

    return {
        rows: number("rows", 1_000_000),
        chunk: number("chunk", 150),
        seed: number("seed", 1),
        timestamp: number("timestamp", Date.now()),
        out: flag("out") ?? resolve(packageDir, "seed/generated/seed.sql"),
    }
}

const main = async () => {
    const options = parseArgs(process.argv.slice(2))

    await mkdir(dirname(options.out), { recursive: true })

    const stream = createWriteStream(options.out)
    let statements = 0

    for (const statement of generateSeedSql(options)) {
        statements++

        if (!stream.write(statement + "\n")) {
            await once(stream, "drain")
        }
    }

    await new Promise<void>((resolveClose) => stream.end(resolveClose))

    console.log(
        `Wrote ${statements} statements to ${options.out} ` +
            `(${options.rows} players, chunk ${options.chunk}, seed ${options.seed}).`,
    )
    console.log(
        "Import it with `pnpm dlx wrangler d1 execute <db> --remote --file=" +
            options.out +
            "` (validate locally with `pnpm db:seed:verify`).",
    )
}

const isMain =
    process.argv[1] !== undefined &&
    resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
    await main()
}
