/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GithubRouteImport } from './routes/github'
import { Route as KofiRouteImport } from './routes/kofi'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TwitterRouteImport } from './routes/twitter'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as AtmeFavoritesRouteImport } from './routes/@me/favorites'
import { Route as ApiBhArticlesRouteImport } from './routes/api/bh-articles'
import { Route as ApiWeeklyRotationRouteImport } from './routes/api/weekly-rotation'
import { Route as CSplatRouteImport } from './routes/c.$'
import { Route as LeaderboardSplatRouteImport } from './routes/leaderboard.$'
import { Route as PSplatRouteImport } from './routes/p.$'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as StatsMeRouteImport } from './routes/stats/me'
import { Route as ApiEffectSplatRouteImport } from './routes/api/effect/$'
import { Route as ApiRankingsIndexRouteImport } from './routes/api/rankings/index'
import { Route as ApiRankingsClansRouteImport } from './routes/api/rankings/clans'
import { Route as ApiRankingsPowerRouteImport } from './routes/api/rankings/power'
import { Route as RankingsClansChar123PageChar125RouteImport } from './routes/rankings/clans.{-$page}'
import { Route as RankingsGlobalChar123PageChar125RouteImport } from './routes/rankings/global.{-$page}'
import { Route as RankingsPowerIndexRouteImport } from './routes/rankings/power/index'
import { Route as StatsClanClanIdRouteImport } from './routes/stats/clan/$clanId'
import { Route as StatsPlayerPlayerIdRouteImport } from './routes/stats/player/$playerId'
import { Route as ApiRankingsSearchPlayerRouteImport } from './routes/api/rankings/search/player'
import { Route as ApiStatsClanClanIdRouteImport } from './routes/api/stats/clan/$clanId'
import { Route as Rankings1v1Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/1v1.{-$region}.{-$page}'
import { Route as Rankings2v2Char123RegionChar125Char123PageChar125RouteImport } from './routes/rankings/2v2.{-$region}.{-$page}'
import { Route as RankingsPowerChar123BracketChar125Char123RegionChar125RouteImport } from './routes/rankings/power.{-$bracket}.{-$region}'
import { Route as ApiStatsPlayerPlayerIdAliasesRouteImport } from './routes/api/stats/player/$playerId/aliases'
import { Route as ApiStatsPlayerPlayerIdRankedRouteImport } from './routes/api/stats/player/$playerId/ranked'
import { Route as ApiStatsPlayerPlayerIdStatsRouteImport } from './routes/api/stats/player/$playerId/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const KofiRoute = KofiRouteImport.update({
  id: '/kofi',
  path: '/kofi',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterRoute = TwitterRouteImport.update({
  id: '/twitter',
  path: '/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmeFavoritesRoute = AtmeFavoritesRouteImport.update({
  id: '/@me/favorites',
  path: '/@me/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBhArticlesRoute = ApiBhArticlesRouteImport.update({
  id: '/api/bh-articles',
  path: '/api/bh-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyRotationRoute = ApiWeeklyRotationRouteImport.update({
  id: '/api/weekly-rotation',
  path: '/api/weekly-rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const CSplatRoute = CSplatRouteImport.update({
  id: '/c/$',
  path: '/c/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardSplatRoute = LeaderboardSplatRouteImport.update({
  id: '/leaderboard/$',
  path: '/leaderboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsMeRoute = StatsMeRouteImport.update({
  id: '/stats/me',
  path: '/stats/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEffectSplatRoute = ApiEffectSplatRouteImport.update({
  id: '/api/effect/$',
  path: '/api/effect/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsIndexRoute = ApiRankingsIndexRouteImport.update({
  id: '/api/rankings/',
  path: '/api/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsClansRoute = ApiRankingsClansRouteImport.update({
  id: '/api/rankings/clans',
  path: '/api/rankings/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsPowerRoute = ApiRankingsPowerRouteImport.update({
  id: '/api/rankings/power',
  path: '/api/rankings/power',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsClansChar123PageChar125Route =
  RankingsClansChar123PageChar125RouteImport.update({
    id: '/rankings/clans/{-$page}',
    path: '/rankings/clans/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsGlobalChar123PageChar125Route =
  RankingsGlobalChar123PageChar125RouteImport.update({
    id: '/rankings/global/{-$page}',
    path: '/rankings/global/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsPowerIndexRoute = RankingsPowerIndexRouteImport.update({
  id: '/rankings/power/',
  path: '/rankings/power/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsClanClanIdRoute = StatsClanClanIdRouteImport.update({
  id: '/stats/clan/$clanId',
  path: '/stats/clan/$clanId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPlayerPlayerIdRoute = StatsPlayerPlayerIdRouteImport.update({
  id: '/stats/player/$playerId',
  path: '/stats/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsSearchPlayerRoute = ApiRankingsSearchPlayerRouteImport.update({
  id: '/api/rankings/search/player',
  path: '/api/rankings/search/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsClanClanIdRoute = ApiStatsClanClanIdRouteImport.update({
  id: '/api/stats/clan/$clanId',
  path: '/api/stats/clan/$clanId',
  getParentRoute: () => rootRouteImport,
} as any)
const Rankings1v1Char123RegionChar125Char123PageChar125Route =
  Rankings1v1Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/1v1/{-$region}/{-$page}',
    path: '/rankings/1v1/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Rankings2v2Char123RegionChar125Char123PageChar125Route =
  Rankings2v2Char123RegionChar125Char123PageChar125RouteImport.update({
    id: '/rankings/2v2/{-$region}/{-$page}',
    path: '/rankings/2v2/{-$region}/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingsPowerChar123BracketChar125Char123RegionChar125Route =
  RankingsPowerChar123BracketChar125Char123RegionChar125RouteImport.update({
    id: '/rankings/power/{-$bracket}/{-$region}',
    path: '/rankings/power/{-$bracket}/{-$region}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStatsPlayerPlayerIdAliasesRoute =
  ApiStatsPlayerPlayerIdAliasesRouteImport.update({
    id: '/api/stats/player/$playerId/aliases',
    path: '/api/stats/player/$playerId/aliases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStatsPlayerPlayerIdRankedRoute =
  ApiStatsPlayerPlayerIdRankedRouteImport.update({
    id: '/api/stats/player/$playerId/ranked',
    path: '/api/stats/player/$playerId/ranked',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStatsPlayerPlayerIdStatsRoute =
  ApiStatsPlayerPlayerIdStatsRouteImport.update({
    id: '/api/stats/player/$playerId/stats',
    path: '/api/stats/player/$playerId/stats',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/api/bh-articles': typeof ApiBhArticlesRoute
  '/api/weekly-rotation': typeof ApiWeeklyRotationRoute
  '/c/$': typeof CSplatRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$': typeof PSplatRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/effect/$': typeof ApiEffectSplatRoute
  '/api/rankings/clans': typeof ApiRankingsClansRoute
  '/api/rankings/power': typeof ApiRankingsPowerRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/api/rankings/': typeof ApiRankingsIndexRoute
  '/rankings/power/': typeof RankingsPowerIndexRoute
  '/api/rankings/search/player': typeof ApiRankingsSearchPlayerRoute
  '/api/stats/clan/$clanId': typeof ApiStatsClanClanIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/{-$bracket}/{-$region}': typeof RankingsPowerChar123BracketChar125Char123RegionChar125Route
  '/api/stats/player/$playerId/aliases': typeof ApiStatsPlayerPlayerIdAliasesRoute
  '/api/stats/player/$playerId/ranked': typeof ApiStatsPlayerPlayerIdRankedRoute
  '/api/stats/player/$playerId/stats': typeof ApiStatsPlayerPlayerIdStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/api/bh-articles': typeof ApiBhArticlesRoute
  '/api/weekly-rotation': typeof ApiWeeklyRotationRoute
  '/c/$': typeof CSplatRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$': typeof PSplatRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings': typeof RankingsIndexRoute
  '/api/effect/$': typeof ApiEffectSplatRoute
  '/api/rankings/clans': typeof ApiRankingsClansRoute
  '/api/rankings/power': typeof ApiRankingsPowerRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/api/rankings': typeof ApiRankingsIndexRoute
  '/rankings/power': typeof RankingsPowerIndexRoute
  '/api/rankings/search/player': typeof ApiRankingsSearchPlayerRoute
  '/api/stats/clan/$clanId': typeof ApiStatsClanClanIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/{-$bracket}/{-$region}': typeof RankingsPowerChar123BracketChar125Char123RegionChar125Route
  '/api/stats/player/$playerId/aliases': typeof ApiStatsPlayerPlayerIdAliasesRoute
  '/api/stats/player/$playerId/ranked': typeof ApiStatsPlayerPlayerIdRankedRoute
  '/api/stats/player/$playerId/stats': typeof ApiStatsPlayerPlayerIdStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/discord': typeof DiscordRoute
  '/donate': typeof DonateRoute
  '/github': typeof GithubRoute
  '/kofi': typeof KofiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter': typeof TwitterRoute
  '/wiki': typeof WikiRoute
  '/@me/favorites': typeof AtmeFavoritesRoute
  '/api/bh-articles': typeof ApiBhArticlesRoute
  '/api/weekly-rotation': typeof ApiWeeklyRotationRoute
  '/c/$': typeof CSplatRoute
  '/leaderboard/$': typeof LeaderboardSplatRoute
  '/p/$': typeof PSplatRoute
  '/stats/me': typeof StatsMeRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/effect/$': typeof ApiEffectSplatRoute
  '/api/rankings/clans': typeof ApiRankingsClansRoute
  '/api/rankings/power': typeof ApiRankingsPowerRoute
  '/rankings/clans/{-$page}': typeof RankingsClansChar123PageChar125Route
  '/rankings/global/{-$page}': typeof RankingsGlobalChar123PageChar125Route
  '/stats/clan/$clanId': typeof StatsClanClanIdRoute
  '/stats/player/$playerId': typeof StatsPlayerPlayerIdRoute
  '/api/rankings/': typeof ApiRankingsIndexRoute
  '/rankings/power/': typeof RankingsPowerIndexRoute
  '/api/rankings/search/player': typeof ApiRankingsSearchPlayerRoute
  '/api/stats/clan/$clanId': typeof ApiStatsClanClanIdRoute
  '/rankings/1v1/{-$region}/{-$page}': typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  '/rankings/2v2/{-$region}/{-$page}': typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  '/rankings/power/{-$bracket}/{-$region}': typeof RankingsPowerChar123BracketChar125Char123RegionChar125Route
  '/api/stats/player/$playerId/aliases': typeof ApiStatsPlayerPlayerIdAliasesRoute
  '/api/stats/player/$playerId/ranked': typeof ApiStatsPlayerPlayerIdRankedRoute
  '/api/stats/player/$playerId/stats': typeof ApiStatsPlayerPlayerIdStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/api/bh-articles'
    | '/api/weekly-rotation'
    | '/c/$'
    | '/leaderboard/$'
    | '/p/$'
    | '/stats/me'
    | '/rankings/'
    | '/api/effect/$'
    | '/api/rankings/clans'
    | '/api/rankings/power'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/api/rankings/'
    | '/rankings/power/'
    | '/api/rankings/search/player'
    | '/api/stats/clan/$clanId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/{-$bracket}/{-$region}'
    | '/api/stats/player/$playerId/aliases'
    | '/api/stats/player/$playerId/ranked'
    | '/api/stats/player/$playerId/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/api/bh-articles'
    | '/api/weekly-rotation'
    | '/c/$'
    | '/leaderboard/$'
    | '/p/$'
    | '/stats/me'
    | '/rankings'
    | '/api/effect/$'
    | '/api/rankings/clans'
    | '/api/rankings/power'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/api/rankings'
    | '/rankings/power'
    | '/api/rankings/search/player'
    | '/api/stats/clan/$clanId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/{-$bracket}/{-$region}'
    | '/api/stats/player/$playerId/aliases'
    | '/api/stats/player/$playerId/ranked'
    | '/api/stats/player/$playerId/stats'
  id:
    | '__root__'
    | '/'
    | '/calc'
    | '/discord'
    | '/donate'
    | '/github'
    | '/kofi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter'
    | '/wiki'
    | '/@me/favorites'
    | '/api/bh-articles'
    | '/api/weekly-rotation'
    | '/c/$'
    | '/leaderboard/$'
    | '/p/$'
    | '/stats/me'
    | '/rankings/'
    | '/api/effect/$'
    | '/api/rankings/clans'
    | '/api/rankings/power'
    | '/rankings/clans/{-$page}'
    | '/rankings/global/{-$page}'
    | '/stats/clan/$clanId'
    | '/stats/player/$playerId'
    | '/api/rankings/'
    | '/rankings/power/'
    | '/api/rankings/search/player'
    | '/api/stats/clan/$clanId'
    | '/rankings/1v1/{-$region}/{-$page}'
    | '/rankings/2v2/{-$region}/{-$page}'
    | '/rankings/power/{-$bracket}/{-$region}'
    | '/api/stats/player/$playerId/aliases'
    | '/api/stats/player/$playerId/ranked'
    | '/api/stats/player/$playerId/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcRoute: typeof CalcRoute
  DiscordRoute: typeof DiscordRoute
  DonateRoute: typeof DonateRoute
  GithubRoute: typeof GithubRoute
  KofiRoute: typeof KofiRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TwitterRoute: typeof TwitterRoute
  WikiRoute: typeof WikiRoute
  AtmeFavoritesRoute: typeof AtmeFavoritesRoute
  ApiBhArticlesRoute: typeof ApiBhArticlesRoute
  ApiWeeklyRotationRoute: typeof ApiWeeklyRotationRoute
  CSplatRoute: typeof CSplatRoute
  LeaderboardSplatRoute: typeof LeaderboardSplatRoute
  PSplatRoute: typeof PSplatRoute
  StatsMeRoute: typeof StatsMeRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ApiEffectSplatRoute: typeof ApiEffectSplatRoute
  ApiRankingsClansRoute: typeof ApiRankingsClansRoute
  ApiRankingsPowerRoute: typeof ApiRankingsPowerRoute
  RankingsClansChar123PageChar125Route: typeof RankingsClansChar123PageChar125Route
  RankingsGlobalChar123PageChar125Route: typeof RankingsGlobalChar123PageChar125Route
  StatsClanClanIdRoute: typeof StatsClanClanIdRoute
  StatsPlayerPlayerIdRoute: typeof StatsPlayerPlayerIdRoute
  ApiRankingsIndexRoute: typeof ApiRankingsIndexRoute
  RankingsPowerIndexRoute: typeof RankingsPowerIndexRoute
  ApiRankingsSearchPlayerRoute: typeof ApiRankingsSearchPlayerRoute
  ApiStatsClanClanIdRoute: typeof ApiStatsClanClanIdRoute
  Rankings1v1Char123RegionChar125Char123PageChar125Route: typeof Rankings1v1Char123RegionChar125Char123PageChar125Route
  Rankings2v2Char123RegionChar125Char123PageChar125Route: typeof Rankings2v2Char123RegionChar125Char123PageChar125Route
  RankingsPowerChar123BracketChar125Char123RegionChar125Route: typeof RankingsPowerChar123BracketChar125Char123RegionChar125Route
  ApiStatsPlayerPlayerIdAliasesRoute: typeof ApiStatsPlayerPlayerIdAliasesRoute
  ApiStatsPlayerPlayerIdRankedRoute: typeof ApiStatsPlayerPlayerIdRankedRoute
  ApiStatsPlayerPlayerIdStatsRoute: typeof ApiStatsPlayerPlayerIdStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kofi': {
      id: '/kofi'
      path: '/kofi'
      fullPath: '/kofi'
      preLoaderRoute: typeof KofiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter': {
      id: '/twitter'
      path: '/twitter'
      fullPath: '/twitter'
      preLoaderRoute: typeof TwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@me/favorites': {
      id: '/@me/favorites'
      path: '/@me/favorites'
      fullPath: '/@me/favorites'
      preLoaderRoute: typeof AtmeFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bh-articles': {
      id: '/api/bh-articles'
      path: '/api/bh-articles'
      fullPath: '/api/bh-articles'
      preLoaderRoute: typeof ApiBhArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-rotation': {
      id: '/api/weekly-rotation'
      path: '/api/weekly-rotation'
      fullPath: '/api/weekly-rotation'
      preLoaderRoute: typeof ApiWeeklyRotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$': {
      id: '/c/$'
      path: '/c/$'
      fullPath: '/c/$'
      preLoaderRoute: typeof CSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$': {
      id: '/leaderboard/$'
      path: '/leaderboard/$'
      fullPath: '/leaderboard/$'
      preLoaderRoute: typeof LeaderboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/me': {
      id: '/stats/me'
      path: '/stats/me'
      fullPath: '/stats/me'
      preLoaderRoute: typeof StatsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/effect/$': {
      id: '/api/effect/$'
      path: '/api/effect/$'
      fullPath: '/api/effect/$'
      preLoaderRoute: typeof ApiEffectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings/': {
      id: '/api/rankings/'
      path: '/api/rankings'
      fullPath: '/api/rankings/'
      preLoaderRoute: typeof ApiRankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings/clans': {
      id: '/api/rankings/clans'
      path: '/api/rankings/clans'
      fullPath: '/api/rankings/clans'
      preLoaderRoute: typeof ApiRankingsClansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings/power': {
      id: '/api/rankings/power'
      path: '/api/rankings/power'
      fullPath: '/api/rankings/power'
      preLoaderRoute: typeof ApiRankingsPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/clans/{-$page}': {
      id: '/rankings/clans/{-$page}'
      path: '/rankings/clans/{-$page}'
      fullPath: '/rankings/clans/{-$page}'
      preLoaderRoute: typeof RankingsClansChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/global/{-$page}': {
      id: '/rankings/global/{-$page}'
      path: '/rankings/global/{-$page}'
      fullPath: '/rankings/global/{-$page}'
      preLoaderRoute: typeof RankingsGlobalChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/power/': {
      id: '/rankings/power/'
      path: '/rankings/power'
      fullPath: '/rankings/power/'
      preLoaderRoute: typeof RankingsPowerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/clan/$clanId': {
      id: '/stats/clan/$clanId'
      path: '/stats/clan/$clanId'
      fullPath: '/stats/clan/$clanId'
      preLoaderRoute: typeof StatsClanClanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/player/$playerId': {
      id: '/stats/player/$playerId'
      path: '/stats/player/$playerId'
      fullPath: '/stats/player/$playerId'
      preLoaderRoute: typeof StatsPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings/search/player': {
      id: '/api/rankings/search/player'
      path: '/api/rankings/search/player'
      fullPath: '/api/rankings/search/player'
      preLoaderRoute: typeof ApiRankingsSearchPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/clan/$clanId': {
      id: '/api/stats/clan/$clanId'
      path: '/api/stats/clan/$clanId'
      fullPath: '/api/stats/clan/$clanId'
      preLoaderRoute: typeof ApiStatsClanClanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/1v1/{-$region}/{-$page}': {
      id: '/rankings/1v1/{-$region}/{-$page}'
      path: '/rankings/1v1/{-$region}/{-$page}'
      fullPath: '/rankings/1v1/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings1v1Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/2v2/{-$region}/{-$page}': {
      id: '/rankings/2v2/{-$region}/{-$page}'
      path: '/rankings/2v2/{-$region}/{-$page}'
      fullPath: '/rankings/2v2/{-$region}/{-$page}'
      preLoaderRoute: typeof Rankings2v2Char123RegionChar125Char123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/power/{-$bracket}/{-$region}': {
      id: '/rankings/power/{-$bracket}/{-$region}'
      path: '/rankings/power/{-$bracket}/{-$region}'
      fullPath: '/rankings/power/{-$bracket}/{-$region}'
      preLoaderRoute: typeof RankingsPowerChar123BracketChar125Char123RegionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/player/$playerId/aliases': {
      id: '/api/stats/player/$playerId/aliases'
      path: '/api/stats/player/$playerId/aliases'
      fullPath: '/api/stats/player/$playerId/aliases'
      preLoaderRoute: typeof ApiStatsPlayerPlayerIdAliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/player/$playerId/ranked': {
      id: '/api/stats/player/$playerId/ranked'
      path: '/api/stats/player/$playerId/ranked'
      fullPath: '/api/stats/player/$playerId/ranked'
      preLoaderRoute: typeof ApiStatsPlayerPlayerIdRankedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/player/$playerId/stats': {
      id: '/api/stats/player/$playerId/stats'
      path: '/api/stats/player/$playerId/stats'
      fullPath: '/api/stats/player/$playerId/stats'
      preLoaderRoute: typeof ApiStatsPlayerPlayerIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcRoute: CalcRoute,
  DiscordRoute: DiscordRoute,
  DonateRoute: DonateRoute,
  GithubRoute: GithubRoute,
  KofiRoute: KofiRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TwitterRoute: TwitterRoute,
  WikiRoute: WikiRoute,
  AtmeFavoritesRoute: AtmeFavoritesRoute,
  ApiBhArticlesRoute: ApiBhArticlesRoute,
  ApiWeeklyRotationRoute: ApiWeeklyRotationRoute,
  CSplatRoute: CSplatRoute,
  LeaderboardSplatRoute: LeaderboardSplatRoute,
  PSplatRoute: PSplatRoute,
  StatsMeRoute: StatsMeRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ApiEffectSplatRoute: ApiEffectSplatRoute,
  ApiRankingsClansRoute: ApiRankingsClansRoute,
  ApiRankingsPowerRoute: ApiRankingsPowerRoute,
  RankingsClansChar123PageChar125Route: RankingsClansChar123PageChar125Route,
  RankingsGlobalChar123PageChar125Route: RankingsGlobalChar123PageChar125Route,
  StatsClanClanIdRoute: StatsClanClanIdRoute,
  StatsPlayerPlayerIdRoute: StatsPlayerPlayerIdRoute,
  ApiRankingsIndexRoute: ApiRankingsIndexRoute,
  RankingsPowerIndexRoute: RankingsPowerIndexRoute,
  ApiRankingsSearchPlayerRoute: ApiRankingsSearchPlayerRoute,
  ApiStatsClanClanIdRoute: ApiStatsClanClanIdRoute,
  Rankings1v1Char123RegionChar125Char123PageChar125Route:
    Rankings1v1Char123RegionChar125Char123PageChar125Route,
  Rankings2v2Char123RegionChar125Char123PageChar125Route:
    Rankings2v2Char123RegionChar125Char123PageChar125Route,
  RankingsPowerChar123BracketChar125Char123RegionChar125Route:
    RankingsPowerChar123BracketChar125Char123RegionChar125Route,
  ApiStatsPlayerPlayerIdAliasesRoute: ApiStatsPlayerPlayerIdAliasesRoute,
  ApiStatsPlayerPlayerIdRankedRoute: ApiStatsPlayerPlayerIdRankedRoute,
  ApiStatsPlayerPlayerIdStatsRoute: ApiStatsPlayerPlayerIdStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
