name: Code QA
on: [push]
jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Check
                      action: pnpm ci:check
                    - name: Check Types
                      action: pnpm ts:check
                    - name: Check Deadcode
                      action: pnpm ci:deadcode
        steps:
            - uses: actions/checkout@v4
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version: "22"
                  cache: true
            - uses: pnpm/action-setup@v4
              with:
                  version: 9.15.9
            - name: ${{ matrix.name }}
              run: |
                  pnpm ci:install
                  ${{ matrix.action }}
