name: Code QA
on: [push]
jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Check
                      action: vp check
                    - name: Check Types
                      action: vp run -r ts:check
        steps:
            - uses: actions/checkout@v4
            - uses: voidzero-dev/setup-vp@v1.21.0
              with:
                  node-version: "24"
                  cache: true
            - name: ${{ matrix.name }}
              run: |
                  vp install
                  ${{ matrix.action }}
