name: Code QA
on: [push]
jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version: "22"
                  cache: true
            - name: Check
              run: |
                  vp install --frozen-lockfile
                  vp run ci:check
